### ISSUE TITLE
初学golang关于map的一点疑问

### ISSUE THREAD

**Issue by yyg2014** [Unknwon/go-fundamental-programming#10]
您讲的例子中 map可以支持多维吗? 无论维度为多少他们的无序性都是一致的对吗？
还有就是关于您讲课的例子中说对一个元素类型为map的slice进行迭代 只是复制value 但是我可以用‘&’；来传递地址循环操作么 是只用一个 ‘&’ 还是要结合 星号 来传递地址呢？

**Comment by Unknwon** [comment]
>您讲的例子中 map可以支持多维吗? 无论维度为多少他们的无序性都是一致的对吗？

支持。都是无序的。

>还有就是关于您讲课的例子中说对一个元素类型为map的slice进行迭代 只是复制value 但是我可以用‘&’；来传递地址循环操作么 是只用一个 ‘&’ 还是要结合 星号 来传递地址呢？

理论上可行，但是可能会增加程序的理解难度，看具体需求了。
