### ISSUE TITLE
是否还有后续视频

### ISSUE THREAD

**Issue by mysterytree** [Unknwon/go-fundamental-programming#11]
看了视频觉得不错 后续是否会有高级应用

**Comment by Unknwon** [comment]
没有还没有计划。。

**Comment by mysterytree** [comment]
谢谢
go感觉还是没有想象的火 
------------
最近做了个聊天室
发现router数量太多 会突然全部挂掉  不知道什么原因

**Comment by mysterytree** [comment]
@Unknwon

**Comment by Unknwon** [comment]
Hi 你的描述太过简陋我基本上没办法帮助你。。。

**Comment by mysterytree** [comment]
goroutine 690 [select]:
main.main.func1(0xc821238a80, 0x0, 0x0)
        /go/src/juliette/server.go:109 +0x93c
juliette/middlewares.Logger.func1.1(0xc821238a80, 0x0, 0x0)
        /go/src/juliette/middlewares/logger.go:27 +0x10e
github.com/labstack/echo.(*Echo).ServeHTTP(0xc8201c8160, 0x7ff7a8ff55c0, 0xc821206840, 0xc820986a80)
        /go/src/github.com/labstack/echo/echo.go:534 +0x28c
net/http.serverHandler.ServeHTTP(0xc820170180, 0x7ff7a8ff55c0, 0xc821206840, 0xc820986a80)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8209e8b00)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6

**Comment by mysterytree** [comment]
无限个这种错误

**Comment by mysterytree** [comment]
@Unknwon

**Comment by Unknwon** [comment]
错误截取的不够完整。

**Comment by mysterytree** [comment]
@Unknwon 其实定位不到什么错误。。。。只是在大篇的刷上边的内容  疯了

**Comment by mysterytree** [comment]
一个http长连接的东西  用了echo做服务器  然后每个链接是一个routing

**Comment by Unknwon** [comment]
那就没办法帮你了。。
