### ISSUE TITLE
应该如何配置sublime，运算符两边就能自动添加空格

### ISSUE THREAD

**Issue by vulohxdelquv** [Unknwon/go-fundamental-programming#16]
老师您好，正在看您的视频教程，受益匪浅。十分感谢。
看到视频演示中，您输入一行代码，回车后代码中一些运算符两边就会自动添加空格，如a:=1，回车后就会自动变成a := 1，觉得这个功能很实用，但自己摸索半天后仍没能实现。
不知应该如何配置，求赐教

**Comment by appleboy** [comment]
@vulohxdelquv gofmt 可以幫忙排版，看你是用什麼編輯器。如果你是用 vscode 請務必裝 https://github.com/Microsoft/vscode-go

**Comment by Unknwon** [comment]
一般就是 gofmt。。跟sublime 本身其实没啥关系。不过你需要装 GoSublime 插件才行。vscode 初学者更加方便点。

**Comment by wu-xian** [comment]
@Unknwon 
为啥vscode初学者更方便？用vscode开发go有什么局限性吗？

**Comment by Unknwon** [comment]
@wu-xian ... 你用了就知道。。没有为啥
