### ISSUE TITLE
关于第7课时slice的问题

### ISSUE THREAD

**Issue by HankWang95** [Unknwon/go-fundamental-programming#17]
```
        s := make([]int, 3, 5)
	fmt.Printf("slice长度为 %d，容量为 %d，地址为 %p\n", len(s), cap(s), &s)
	s = append(s, 1, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3)
	fmt.Printf("s变成了%v，容量为%d，地址变成了%p\n", s, cap(s), &s)
```
输出：
        slice长度为 3，容量为 5，地址为 0xc42000a080
	s变成了[0 0 0 1 2 2 3 2 3 3 3 3 3 3]，容量为14，地址变成了0xc42000a080

结论：
        可能是因为go语言版本更新等问题，并没有出现视频中所说的容量翻倍问题，而是直接做加法。并且内存地址也没有变化，应该是直接在原地做了容量增加的操作。希望能提醒下大家。
感谢无闻以及所做的视频，简单易懂，收获很大👍👍

**Comment by Unknwon** [comment]
新版本的 go 可能对自动扩展做出了一些改动，那就需要读源码啦。嘿嘿
