### ISSUE TITLE
强烈建议作者上传一份到bilibili

### ISSUE THREAD

**Issue by jiaoqiyuan** [unknwon/go-fundamental-programming#25]
bilibili没广告，体验好，pls

**Comment by unknwon** [comment]
啊哈哈，我没有权限呀，另外应该有好心的同学传过了。https://search.bilibili.com/all?keyword=go%20%E7%BC%96%E7%A8%8B%E5%9F%BA%E7%A1%80&from_source=banner_search

**Comment by jiaoqiyuan** [comment]
嗯嗯
