### ISSUE TITLE
go web交流群搜索不到呢，是解散了么？

### ISSUE THREAD

**Issue by Famine-Life** [unknwon/go-fundamental-programming#26]
go web交流群搜索不到呢，是解散了么？

**Comment by unknwon** [comment]
老哥你可能搜成联系人了吧。。

**Comment by Famine-Life** [comment]
老铁，
259316004

复制粘贴过来的，你搜搜

---原始邮件---
发件人: "Unknwon"<notifications@github.com&gt;
发送时间: 2019年11月13日(星期三) 中午12:26
收件人: "unknwon/go-fundamental-programming"<go-fundamental-programming@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"练涛"<xanwidtf@foxmail.com&gt;;
主题: Re: [unknwon/go-fundamental-programming] go web交流群搜索不到呢，是解散了么？ (#26)



老哥你可能搜成联系人了吧。。

**Comment by unknwon** [comment]
奇奇怪怪的。。我也搜不到了，我直接在 README 贴个二维码吧！

**Comment by unknwon** [comment]
![IMG_2312](https://user-images.githubusercontent.com/2946214/68735685-51dd2400-0593-11ea-9bff-d5985990753c.JPG)
