### ISSUE TITLE
第10课里struct内嵌结构字面量声明的问题

### ISSUE THREAD

**Issue by kuuyee** [Unknwon/go-fundamental-programming#8]
首先感谢无闻老师精彩的课程。

在学习第10课 struct结构时，其中讲解到内嵌struct字面量声明部分（视频第28分钟），无闻老师对于下面的声明解释我觉得没有说清楚，也可能是我没有理解清楚：

```
a := teacher{Name: "joe", Age: 19, human{Sex: 1}}
```

对于编译不过，老师的解释是需要声明为`human: human{Sex: 1}`才对，但是我仔细看了报错信息：

```
error:
mixture of field:value and value initializers
exit status 2
```
大致的意思是说，这个错误的原因是用了`field:value`和`value`混合的声明，所以解决这个错误我用了另一个方式：

```
a := teacher{"joe", 19, human{Sex: 1}}
```

这是我这个菜鸟的一点拙见，请无闻老师指正！

**Comment by Unknwon** [comment]
@kuuyee 感谢提问！其实你的解决方法是一样的。。视频中是补全的字段名称。。而你是删掉了其他的字段名称。。结果就是格式都统一了，于是可以编译了

**Comment by kuuyee** [comment]
嗯！
请教下无闻老师，目前有用Go语言实现的开源持续集成应用吗，就像是Jenkins一类的应用。有的话推荐一个，谢谢！

**Comment by Unknwon** [comment]
有啊。。比如国外的 https://github.com/drone/drone 和国内的 https://github.com/ArchCI/archci
